# Generated by Django 5.1.7 on 2025-04-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rollno', models.IntegerField()),
                ('marks', models.FloatField()),
                ('addr', models.CharField(max_length=30)),
                ('phno', models.IntegerField()),
            ],
        ),
    ]
